FROM fukamachi/qlot

WORKDIR /app

COPY qlfile /app
COPY qlfile.lock /app

RUN set -x; \
  qlot install --no-deps

FROM fukamachi/sbcl:2.1.8

WORKDIR /app

COPY --from=0 /app/.qlot /app/.qlot
COPY . /app

RUN set -x; \
  ros -l .qlot/setup.lisp -S . -s dist-updater \
    -e '(asdf:make :dist-updater/executable)'

ENTRYPOINT ["/app/entrypoint.sh"]
