name: CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test image
        run: |
          make build_test
      - name: Run all tests
        run: |
          make test
